site_name: Rakesh Portfolio
site_description: Rakesh Hadne Sreenath — AI Engineer | LLM & Agentic Systems | MLOps
site_author: Rakesh Hadne Sreenath
repo_url: https://github.com/Rakesh-Seenu/resume_mkdocs

nav:
  - Home: index.md
  - Experience: experience.md
  - Skills & Tech-stack: skills.md
  - Projects Undertaken: projects.md
  - Publications: publications.md
  - Education: education.md
  - Achievements & Certifications: recognition.md
  - Interests & Hobbies: interests.md
  - About Me: about.md
  - Downloads: download.md

theme:
  name: material
  features:
    - navigation.tracking
    - navigation.footer
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.tabs.link
  favicon: images/favicon.png
  icon:
    logo: material/seed
  language: en
  font:
    text: Google Sans
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rakesh-hs
      name: LinkedIn
    - icon: fontawesome/brands/github
      link: https://github.com/Rakesh-Seenu
      name: GitHub
    - icon: fontawesome/solid/envelope
      link: mailto:hsrakesh71@gmail.com
      name: Email

copyright: Copyright &copy; 2026 &nbsp;RAKESH HADNE SREENATH

markdown_extensions:
  - tables
  - abbr
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - attr_list
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - tags
